package com.myspace.mortgage_app;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InlimtError implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Inlimit Error")
	private java.lang.String inlimtError;

	public InlimtError() {
	}

	public java.lang.String getInlimtError() {
		return this.inlimtError;
	}

	public void setInlimtError(java.lang.String inlimtError) {
		this.inlimtError = inlimtError;
	}

	public InlimtError(java.lang.String inlimtError) {
		this.inlimtError = inlimtError;
	}

}